<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1541223442092" stop="1541223560209">
	<name>Customer</name>
	<title>Customer</title>
	<test-cases>
		<test-case start="1541223442092" stop="1541223450206" status="passed">
			<name>LoginPage</name>
			<title>LoginPage</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
		<test-case start="1541223450206" stop="1541223466038" status="passed">
			<name>VerifyCurrencyType2</name>
			<title>VerifyCurrencyType2</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
		<test-case start="1541223466038" stop="1541223481647" status="passed">
			<name>InitialTransaction3</name>
			<title>InitialTransaction3</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
		<test-case start="1541223481647" stop="1541223490609" status="passed">
			<name>DepositMoney4</name>
			<title>DepositMoney4</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
		<test-case start="1541223490609" stop="1541223506721" status="passed">
			<name>TransactionAfterDeposit5</name>
			<title>TransactionAfterDeposit5</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
		<test-case start="1541223506721" stop="1541223517947" status="failed">
			<name>withdrawError6</name>
			<title>withdrawError6</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
			<failure>
				<message>Expected &apos;Transaction successful&apos; to equal &apos;Transaction Failed. You can not withdraw amount more than the balance.&apos;.</message>
				<stack-trace>Error: Failed expectation
    at UserContext.&lt;anonymous&gt; (C:\Users\prade\eclipse-workspace\AProtractor\src\BankingApp\Customer.js:164:27)
    at C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7</stack-trace>
			</failure>
		</test-case>
		<test-case start="1541223517947" stop="1541223529046" status="failed">
			<name>withdrawSuccess7</name>
			<title>withdrawSuccess7</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
			<failure>
				<message>Expected &apos;Transaction Failed. You can not withdraw amount more than the balance.&apos; to equal &apos;Transaction successful&apos;.</message>
				<stack-trace>Error: Failed expectation
    at UserContext.&lt;anonymous&gt; (C:\Users\prade\eclipse-workspace\AProtractor\src\BankingApp\Customer.js:186:25)
    at C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\prade\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7</stack-trace>
			</failure>
		</test-case>
		<test-case start="1541223529046" stop="1541223545112" status="passed">
			<name>TransactionAfterWithdraw8</name>
			<title>TransactionAfterWithdraw8</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
		<test-case start="1541223545112" stop="1541223560208" status="passed">
			<name>TransactionAfterReset9</name>
			<title>TransactionAfterReset9</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
	</test-cases>
</ns2:test-suite>